### ISSUE TITLE
“App <name> has not been deployed”

### ISSUE THREAD

**Issue by bfontaine** [jezdez/dokku-elasticsearch-plugin#14]
Hello, following your README I create a container but I get “App esdb has not been deployed” (`esdb` is the name of the created container).

```
$ ssh dokku@<host> elasticsearch:create esdb
Warning: '-name' is deprecated, it will be replaced by '--name' soon. See usage.
8560f9b3aa7c4c7cef6d9d8770e7919d2fa7160623a511c9280becb155c760bc
-----> Creating /home/dokku/esdb/LINK
-----> Linking elasticsearch_esdb:elasticsearch with esdb
-----> Setting config vars and restarting esdb
       ELASTICSEARCH_URL: http://172.17.1.100:9200
App esdb has not been deployed
-----> esdb linked to elasticsearch_esdb container
-----> Elasticsearch container created: elasticsearch_esdb

       Host: 172.17.1.100
       Private ports: 9200, 9300

Connection to <host> closed.
```

Tried to get the logs:

```
$ dokku logs esdb
Application's container not found
```

Update: `~dokku/esdb` exists, but it doesn’t have a `CONTAINER` file.

**Comment by sportsy** [comment]
Did you ever figure this out?

**Comment by bfontaine** [comment]
IIRC, I ran [the command](https://github.com/jezdez/dokku-elasticsearch-plugin/blob/master/commands#L70-L71) by hand (with the correct parameters) and it solved the problem.

**Comment by fiatjaf** [comment]
This happens when you `git push` before creating the app with `dokku apps:create <name>`.

I don't know why.
The only solution I found was to destroy the app, then create it, then push.

**Comment by sillygwailo** [comment]
When I encountered this message, I ran `dokku ps:scale [appname] [procname]=1` (replace `1` for the amount of processes you want) to get the container up and running.
